"""
Custom Jinja filters for OpenConfig templates.

:codeauthor: Criteo Network team
:maturity:   new
"""

def format_route_policy_name(route_policy_name, afisafi):
    """Format route policy name.

    :param route_policy_name: the name of the route policy
    :param afisafi: the AFI/SAFI name the route policy belongs to
    """
    if not afisafi:
        return route_policy_name
    return "AUTOGENERATED::{}::{}".format(route_policy_name, afisafi.upper())
